[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
on_event = 'BufRead'
hook_add = '''
	nmap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>
	nmap <silent> <C-u><C-p> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
	nmap <silent> <C-u><C-j> :<C-u>Denite line<CR>
	nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
	nmap <silent> <C-u><C-]> :<C-u>DeniteCursorWord grep<CR>
	nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
	nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
	nmap <silent> <C-u><C-r> :<C-u>Denite -resume<CR>
	nmap <silent> <C-u>; :<C-u>Denite -resume -immediately -select=+1<CR>
	nmap <silent> <C-u>- :<C-u>Denite -resume -immediately -select=-1<CR>
	nmap <silent> <C-u><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
	nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>

	" nnoremap <silent> / :<C-u>Denite -buffer-name=search -auto-resize line<CR>
'''
hook_post_source = '''
	call denite#custom#option('default', 'prompt', '>')
	" denite/insert モードのときは、C- で移動できるようにする
	call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
	call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
	" tabopen や vsplit のキーバインドを割り当て
	call denite#custom#map('insert', "<C-n>", '<denite:do_action:tabopen>')
	call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
	call denite#custom#map('normal', "t", '<denite:do_action:tabopen>')
	call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')
	" jj で denite/insert を抜けるようにする
	call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

	call denite#custom#var('file_rec', 'command', ['rg', '--files', '--glob', '!.git'])
	call denite#custom#var('grep', 'command', ['rg'])
	call denite#custom#var('grep', 'default_opts', [])
	call denite#custom#var('grep', 'recursive_opts', [])
'''

# JavaScriptのシンタクスハイライト
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# JavaScriptのインデント
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

# コーヒースクリプトシンタックス
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['javascript']

# jQuery
[[plugins]]
repo = 'vim-scripts/jQuery'
on_ft = ['javascript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['html']

# html5シンタックス
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html','css']


# 選択後 :SQLUFormatter でSQL整形
[[plugins]]
repo = 'vim-scripts/SQLUtilities'
on_cmd = ['SQLUFormatter']

# :JSHintコマンドによるJS文法チェック
[[plugins]]
repo = 'walm/jshint.vim'
on_cmd = ['JSHint']

# <Leader>rで:QuickRunという言語ごとの実行コマンド
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']

# :Gitvコマンドでgit操作
[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = ['Gitv','Gitv!']

# :Unite outlineコマンドでアウトラインを表示
[[plugins]]
repo = 'h1mesuke/unite-outline'
on_cmd = ['Unite outline']

# :Unite sshコマンドssh
[[plugins]]
repo = 'Shougo/unite-ssh'
on_cmd = ['Unite ssh']

# :Ag コマンドでag
[[plugins]]
repo = 'rking/ag.vim'
on_cmd = ['Ag']

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','mkd']

# quote内のプログラムをシンタックスハイライトする
[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# :PrevimOpen で 編集中のMarkdownファイルのプレビューを作成する
[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown','mkd']

# プレビューをブラウザで開いてくれる
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','mkd']

# EasyMotion
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
	" デフォルトのキーマッピングを無効に
	let g:EasyMotion_do_mapping = 0

	" nmap s <Plug>(easymotion-s2)
	" xmap s <Plug>(easymotion-s2)
	" omap z <Plug>(easymotion-s2)
	" nmap g/ <Plug>(easymotion-sn)
	" xmap g/ <Plug>(easymotion-sn)
	" omap g/ <Plug>(easymotion-tn)
	let g:EasyMotion_smartcase = 1
	map <Leader>j <Plug>(easymotion-j)
	map <Leader>k <Plug>(easymotion-k)
	let g:EasyMotion_startofline = 0
	let g:EasyMotion_keys = 'QZASDFGHJKL;'
	let g:EasyMotion_use_upper = 1
	" let g:EasyMotion_enter_jump_first = 1
	" let g:EasyMotion_space_jump_first = 1
	" hi EasyMotionTarget guifg=#80a0ff ctermfg=81

	" s + 2文字 で画面全体を検索してジャンプ
	nmap s <plug>(easymotion-overwin-f2)
	" 検索時、大文字小文字を区別しない
	let g:EasyMotion_smartcase = 1
	hi EasyMotionTarget guifg=#80a0ff ctermfg=81
'''
